image:
  repository: 968909453204.dkr.ecr.eu-central-1.amazonaws.com/laptopai-ai-service
  tag: 7b2ee13be2c7995cc541ebb46c9edeb5066c27b5

replicaCount: 1
namespace: dev
redisUrl: redis://redis:6379
aiModel: gemini-1.5-flash
geminiApiKey: "PLACEHOLDER"