image:
  repository: 968909453204.dkr.ecr.eu-central-1.amazonaws.com/laptopai-ai-service
  tag: ef7e03b5b7c631cf40b91aafe7ee60b6654f48d8

replicaCount: 1
namespace: dev
redisUrl: redis://redis:6379
aiModel: gpt-4o-mini