image:
  repository: 968909453204.dkr.ecr.eu-central-1.amazonaws.com/laptopai-backend
  tag: 4a9237ac7a9a1c0ac5a2e609533d0928c91e7263

replicaCount: 1
namespace: dev

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.laptopai.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: api-laptopai-tls-secret
      hosts:
        - api.laptopai.dev