image:
  repository: 968909453204.dkr.ecr.eu-central-1.amazonaws.com/laptopai-backend
  tag: 7ae1269262d50b1630c5218623008e2711dade10

replicaCount: 1
namespace: dev

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.laptopai.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: api-laptopai-tls-secret
      hosts:
        - api.laptopai.dev