image:
  repository: 968909453204.dkr.ecr.eu-central-1.amazonaws.com/laptopai-backend
  tag: 929aa9c6521e45d09c749c5dca46a4a8291fa9e7

replicaCount: 1
namespace: dev

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.devopsai.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: api-devopsai-tls-secret
      hosts:
        - api.devopsai.dev