apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laptopai-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.1.1
    helm:
      valueFiles:
        - values.yaml
      values: |
        grafana:
          adminPassword: "LaptopAI2024"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true