name: Terraform Plan

on:
  pull_request:
    paths: ['infra/**']

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform plan in progress
        run: echo "Terraform plan буде налаштований пізніше"