image:
  repository: 968909453204.dkr.ecr.eu-central-1.amazonaws.com/laptopai-frontend
  tag: 4a9237ac7a9a1c0ac5a2e609533d0928c91e7263

replicaCount: 1
namespace: dev
backendUrl: "http://backend:8000"  # For server-side requests

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: laptopai.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: laptopai-tls-secret
      hosts:
        - laptopai.dev