image:
  repository: 968909453204.dkr.ecr.eu-central-1.amazonaws.com/laptopai-frontend
  tag: f63ba758f20fd148fac85f1fdaa715116e310e3c

replicaCount: 1
namespace: dev
apiUrl: http://backend:8000
publicIp: "63.182.162.11"